url: http://stuykc.org
exclude: ['README.md', 'CNAME', 'bootstrap', 'Gemfile', 'test']
permalink: /events/:year/:month/:day/:title
paginate: 10
paginate_path: /events/page:num

gems:
    - jekyll-redirect-from
markdown: kramdown
